### ISSUE TITLE
remote <server> line missing in generated OpenVPN configuration

### ISSUE THREAD

**Issue by ralgozino** [sighupio/furyagent#19]
When generating an OpenVPN configuration file using the following command:

```bash
furyagent configure openvpn-client --config openvpn-furyagent.yml --client-name myname > myname.ovpn
```

and if in the `openvpn-furyagent.yml` the Server section is missing, then `furyagent` instead of failing, generates an OpenVPN configuration without the `remote <server>` line, so the openvpn client doesn't know where to connect to.

**Comment by iknite** [comment]
https://github.com/sighupio/furyagent/blob/master/pkg/component/openvpnclient.go#L54 strangely the template has the required part

**Comment by lnovara** [comment]
I think that the issue is related to behavior of `mapstructure` that if it does not find the `servers` key does not complain and the `range` in the template stays empty.

Ref: https://github.com/sighupio/furyagent/blob/master/pkg/component/component.go#L90

**Comment by iknite** [comment]
Can you give us the config you've been using? @ralgozino

**Comment by ralgozino** [comment]
It has sensitive information. I'll get in touch in private.
